name: Create Release Notes PR
on:
  release:
    types: [published]

jobs:
  add-release-notes:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Generate release notes
        uses: pantheon-systems/action-release-notes@main
        with:
          token: ${{ secrets.TOKEN }}
          github_token: ${{ secrets.TOKEN }}
          docs_repo: jazzsequence/documentation
          repo_name: Plugin Pipeline Example
          categories: wordpress,plugins